# Generated by Django 6.0 on 2025-12-05 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('edificio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('capacidad', models.PositiveIntegerField(default=30)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='edificio.edificio')),
            ],
        ),
    ]
