# Generated by Django 6.0 on 2025-12-05 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aula', '0001_initial'),
        ('curso', '0001_initial'),
        ('profesor', '0001_initial'),
        ('semestre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_texto', models.CharField(help_text='Ej: Lunes y Miércoles 10:00-11:30', max_length=100)),
                ('aula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aula.aula')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='curso.curso')),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profesor.profesor')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semestre.semestre')),
            ],
            options={
                'verbose_name': 'Sesión de Clase',
                'verbose_name_plural': 'Sesiones de Clases',
            },
        ),
    ]
