# Generated by Django 6.0 on 2025-12-05 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clasesesion', '0001_initial'),
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('clase_sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clasesesion.clasesesion')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.estudiante')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'unique_together': {('estudiante', 'clase_sesion')},
            },
        ),
    ]
