# Generated by Django 6.0 on 2025-12-05 19:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matricula', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Calificación de 0.00 a 10.00', max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('comentarios', models.TextField(blank=True)),
                ('matricula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='matricula.matricula')),
            ],
            options={
                'verbose_name': 'Calificación Final',
                'verbose_name_plural': 'Calificaciones Finales',
            },
        ),
    ]
